Revise JettyCat tutorial to use v2 features and update screenshots
ct-js/docs.ctjs.rocks pull request #77
Opened 2022-07-19 02:49 UTC by firecakes

This PR updates the JettyCat tutorial, both the making and polishing pages. Screenshots have been updated to show the new UI on ct.js, new concepts have been explained, code snippets have been updated to use the new APIs, and grammatical errors have been fixed.

The only thing I was unable to change is the FX section in the polishing page where there is a reference to a `Circle_08` texture that I could not find, so I left it as is.

2022-07-19 02:55 UTC, CosmoMyzrailGorynych commented on docs/tut-polishing-jettycat.md
> +The game is complete mechanic-wise, but there is a lot of ways to improve it aesthetically and gameplay-wise! This section also highlights some v1.3 features.
I think the sentence with `v1.3` may be completely removed already 🙃

2022-07-19 02:59 UTC, CosmoMyzrailGorynych commented on docs/tut-making-jettycat.md
> +* We will add a Pointer event that, when executed, will accelerate the cat so that it can fly up.
But it's not a pointer event; it is an action event

2022-07-19 03:02 UTC, CosmoMyzrailGorynych commented on docs/tut-making-jettycat.md
> +Add this code to the cat's Frame start event:
This piece of code can be replaced with Action Down event, removing the  `if` clause.

2022-07-19 03:03 UTC, CosmoMyzrailGorynych commented on docs/tut-making-jettycat.md
> +Ct.js has an entity `ct.camera` which is responsible for showing stuff on your screen. It has lots of features, and one of them is following a template.
Camera does follow individual copies

2022-07-19 03:04 UTC, CosmoMyzrailGorynych commented on docs/tut-making-jettycat.md
> +`ct.place.occupied` checks for a collision of a given copy with a specific collision group. This method is provided by `ct.place module`, and you can find its reference for other methods in the "Catm
`ct.place module`... why did the formatting change here?

2022-07-19 03:06 UTC, CosmoMyzrailGorynych commented on docs/tut-making-jettycat.md
>  Like templates, rooms can have their own logic as well — they are hidden under the button "Room events" in a room editor. There are four events as well:
There are also timers as well, and action events. Maybe this paragraph and list should be removed or rephrased.

2022-07-19 03:08 UTC, CosmoMyzrailGorynych commented on docs/tut-making-jettycat.md
> +3. Add a bit of logic to the star's "Frame start" event that will destroy the star when colliding with the cat.
This can *(and should)* be replaced with a "collision with a template" event from ct.place

2022-07-19 03:10 UTC, CosmoMyzrailGorynych commented on docs/tut-making-jettycat.md
>  ```js
I think use the collision event but note the alternative way with `ct.place.meet` in a tip after the main instruction.

Tips can be created with
```
::: tip
these
:::
```

2022-07-19 03:12 UTC, CosmoMyzrailGorynych commented on docs/tut-making-jettycat.md
> +After that, create a new template with this texture. In its Frame start code, put the following:
Can _(and should)_ be replaced with Pointer Click event. These events do not depend on catmods, btw, so they are recommended for general usage when coordinates and other values are not relevant. And if they are, there is always ct.pointer.

2022-07-19 03:12 UTC, CosmoMyzrailGorynych commented on docs/tut-making-jettycat.md
> +if (ct.pointer.collidesUi(this)) {
Same as in the previous case

2022-07-19 03:14 UTC, CosmoMyzrailGorynych commented on docs/tut-making-jettycat.md
> +After that, create two new templates similar to those created for `MainMenu`. Use textures `Button_Play` and `Jetty_Cat`. The button should be called `Button_Continue`, though.
Mmmmm nope, there is a texture `Pause` for the pause screen, different from the title screen

2022-07-19 03:31 UTC, CosmoMyzrailGorynych requested changes
You were quite throughout! 👍👏 
There are several places where I strongly recommend code simplification with the usage of new events. And a few where it isn't quite important.
There are other various tiny problems with needed.

Ping me on Discord if you have any questions or ideas.

2022-07-21 04:19 UTC, firecakes commented
@CosmoMyzrailGorynych Applied updates, and ready for re-review.

2022-07-21 06:21 UTC, CosmoMyzrailGorynych approved these changes

2022-07-21 06:24 UTC, merged